### PR TITLE
#170947423 integrates hound ci with badge in the repo

### PR DESCRIPTION
**Pull request by izzett222**
#### What does this PR do?
- Integrate HoundCI with a badge attached to the readme
#### Description of Task to be completed?
- added .hound.yml file
- added the hound badge on the readme
#### How should this be manually tested?
N/A
#### What are the relevant pivotal tracker stories?
#170947423
#### Questions:

### CODE REVIEW

**Review by RusimbiPatrick — DISMISSED** [review]
No newline at the end(ESlint)

**Comment by AbdoulNuru** [comment]
> No newline at the end(ESlint)

@Patrick I think it is because you guys don't have ESLint yet since my PR is not merged yet.

**Review by AbdoulNuru — APPROVED** [review]

**Comment by RusimbiPatrick** [comment]
> > No newline at the end(ESlint)
> 
> @patrick I think it is because you guys don't have ESLint yet since my PR is not merged yet.

**Comment by RusimbiPatrick** [comment]
> > > No newline at the end(ESlint)
> > 
> > 
> > @patrick I think it is because you guys don't have ESLint yet since my PR is not merged yet.
Okay, Probably

**Review by hakoemmy — APPROVED** [review]

**Review by RusimbiPatrick — APPROVED** [review]

**Review by blaise82 — APPROVED** [review]

**Review by kcharles52 — APPROVED** [review]

**Pull request merged**
