### PR TITLE
#171178620 Create pull request template

### PR DESCRIPTION
**Pull request by AbdoulNuru**
#### What does this PR do?

- Create the pull request template. 

#### How should this be manually tested?

- In your project's root directory there is a folder called `.github` inside that folder, you will find a file called `pull-request.template.md`, use the template to write pull request that adheres to Andela conventions

#### Implementation plan

N/A

#### Stories associated with PR

[#171178620](https://www.pivotaltracker.com/story/show/171178620)

#### Screenshots if any
N/A

### CODE REVIEW

**Review by hakoemmy — CHANGES_REQUESTED** [review]
Thanks @AbdoulNuru , this is a great initiative to setup pull request template.

But I am afraid, we won't be able to get this template loaded on a fly-in creation of upcoming PRs 

I think you can try this way:
1.  Create a new folder called ``` .github ``` in the root directory
2. Inside that folder, add a file called `` PULL_REQUEST_TEMPLATE.md ``
3. Then push it
``` PULL_REQUEST_TEMPLATE.md ```
```suggestion

  ### What does this PR do?

- 
- 

### How should this be manually tested?

- 
-

### Implementation plan

[Implementation plan name](link to the implementation plan document)

### Stories associated with PR

[#0000](https://www.pivotaltracker.com/story/show/0000)

### Screenshots if any
```

**Review by hakoemmy — CHANGES_REQUESTED** [review]
Again, take a close look at how you named the branch, 
There are a quite small mistyped symbol and the order of words as well: ``` ch/171178620-pull-request-template ```
You should correct it to ```ch-pull-request-template-171178620

**Comment by AbdoulNuru** [comment]
> Again, take a close look at how you named the branch,
> There are a quite small mistyped symbol and the order of words as well: `ch/171178620-pull-request-template`
> You should correct it to ```ch-pull-request-template-171178620

@hakoemmy check our wiki

**Comment by AbdoulNuru** [comment]
> Thanks @AbdoulNuru , this is a great initiative to setup pull request template.
> 
> But I am afraid, we won't be able to get this template loaded on a fly-in creation of upcoming PRs
> 
> I think you can try this way:
> 
> 1. Create a new folder called `.github` in the root directory
> 2. Inside that folder, add a file called `PULL_REQUEST_TEMPLATE.md`
> 3. Then push it
>    `PULL_REQUEST_TEMPLATE.md`
> 
> ```
> 
>   ### What does this PR do?
> 
> - 
> - 
> 
> ### How should this be manually tested?
> 
> - 
> -
> 
> ### Implementation plan
> 
> [Implementation plan name](link to the implementation plan document)
> 
> ### Stories associated with PR
> 
> [#0000](https://www.pivotaltracker.com/story/show/0000)
> 
> ### Screenshots if any
> ```

Thank you @hakoemmy, I implemented the changes.

**Review by hakoemmy — APPROVED** [review]

**Comment by hakoemmy** [comment]
> > Again, take a close look at how you named the branch,
> > There are a quite small mistyped symbol and the order of words as well: `ch/171178620-pull-request-template`
> > You should correct it to ```ch-pull-request-template-171178620
> 
> @hakoemmy check our wiki

ooh sorry, I messed this convention with [Andela best practices](https://github.com/andela/bestpractices/wiki/Git-naming-conventions-and-best-practices)

**Review by blaise82 — APPROVED** [review]

**Review by kcharles52 — APPROVED** [review]

**Pull request merged**
